# fly.toml app configuration file generated for pelada-do-humor on 2025-06-08T05:42:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pelada-do-humor'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
